// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkpzreixrbdvgldorchu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrcHpyZWl4cmJkdmdsZG9yY2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNDM0OTUsImV4cCI6MjA3NTcxOTQ5NX0.lWYYiu_FsTNsET-2_WhS9M1uBpz3JnIjE7u7nWQtnz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});